# Generated by Django 3.0.8 on 2020-07-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='name',
        ),
    ]
