# Generated by Django 3.0.8 on 2020-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200729_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currentPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
