# Generated by Django 3.0.8 on 2020-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_item_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
    ]
